# true colours support
# set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# # underscore colours - needs tmux-3.0
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# enable mouse in tmux session
set -g mouse on

# WE DON'T NEED THESE ON FOR NOW True color settings
#set -g default-terminal "$TERM"
#set -ag terminal-overrides ",$TERM:Tc"

#set -g pane-border-status top
#set -g pane-border-format " #{pane_index} | #{pane_current_command} "

# Statusline location
#set -g status-position bottom

# STATUS LINE STYLES
set -g status-bg "#111111"
set -g status-fg white

# Inactive window
set -g window-status-style fg=#9EACAC
#set -g window-status-style fg=#4c4f4c

# Current window name 
set -g window-status-current-style fg=#000000,bold,italics,bg=colour214,bright

set -g status-interval 1

set -g status-right "#{prefix_highlight} | %I:%M:%S %p, %d-%b-%y, %a"

# Increase left length
set -g status-left-length 150

# Increase right length
set -g status-right-length 150

set -g base-index 1

set -g renumber-windows on

set -g repeat-time 600

# KEY BINDINGS
unbind-key C-b
set-option -g prefix C-space
bind-key C-space send-prefix

bind-key C-c new-window
bind-key g split-window -h
bind-key v split-window -v
bind-key BSpace previous-window
bind-key Tab next-window

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

bind-key -r n next-window
bind-key -r p previous-window

bind-key q display-panes -d 0
bind-key 1 select-window -t 1
bind-key 2 select-window -t 2
bind-key 3 select-window -t 3
bind-key 4 select-window -t 4
bind-key 5 select-window -t 5
bind-key 6 select-window -t 6
bind-key 7 select-window -t 7
bind-key 8 select-window -t 8
bind-key 9 select-window -t 9
bind-key u kill-pane
bind-key x kill-window

#bind-key -r f run-shell "tmux neww tmux-sessionizer"

bind-key -n M-s run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 100%,100% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
#set -g @plugin 'tmux-plugins/tmux-pain-control'

#set -g @plugin 'omerxx/tmux-floax'#
#set -g @floax-bind '-n M-p'
#set -g @floax-bind-menu 'P'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
